### ISSUE TITLE
Custom Trade Element

### ISSUE THREAD

**Issue by AAli107** [Team-MCToolkit/MCToolkit#151] opened 2020-12-06 17:38 UTC
**Describe the feature**

A new Element called "Custom Trade" allows users to add a custom trading option that can appear in a certain type of villager and at a certain level both inputted by the user/mod developer.

**How would you implement it?**

An entirely new Mod Element for custom trade.

**Additional context**

How long do you guys think it'll take to make this new mod element?

**Comment by Max094Reikeb** [comment] 2020-12-06 19:20
This issue could be linked to issue #58! There should be a villager mod element, where you could create your custom villager job, and you could link the villager to a trade mod element that could add/modify trades for a custom or vanilla villager.

**Comment by Blackout03** [comment] 2020-12-06 22:54
Duplicate of #58

**Closed by Blackout03** 2020-12-06 22:54 UTC
Labels: new feature

**Comment by Max094Reikeb** [comment] 2020-12-06 22:56
> Duplicate of #58

No it's not a dupplicate of 58, this feature request is about a custom trade mod element, while 58 is about a Custom Villager mod element. Custom trades are useful to add trades to existing villagers.

**Comment by Blackout03** [comment] 2020-12-06 22:59
That is literally what this element is about "add a custom trading option that can appear in a certain type of villagerr= and at a certain level"

This is how 1.14+ villagers work, they have levels

**Comment by AAli107** [comment] 2020-12-06 22:59
My idea is closed?

**Comment by AAli107** [comment] 2020-12-07 05:07
> That is literally what this element is about "add a custom trading option that can appear in a certain type of villagerr= and at a certain level"
> 
> This is how 1.14+ villagers work, they have levels

I meant that users/mod developers will be able to choose the level at which the trade appears, not add a level system.

**Comment by Blackout03** [comment] 2020-12-07 05:22
That is exactly what I said I never mentioned adding a custom level system...
