### ISSUE TITLE
Hopper block base

### ISSUE THREAD

**Issue by carly6040** [Team-MCToolkit/MCToolkit#307] opened 2021-07-12 12:11 UTC
**Describe the feature**
This would add a hopper blockbase that works like the hopper does.
You would have to make the UI on your own.
It would just work like following: It just moves stuff in it's slots to whatever block it should be connected to.

**How would you implement it?**
Block base

**Additional context**
There could also be a setting under tile entity called: Acts like hopper

**Comment by Max094Reikeb** [comment] 2021-07-12 16:42
Duplicate of #62

**Closed by Max094Reikeb** 2021-07-12 16:42 UTC
